# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Upper Calder Valley Renaissance Flood Response
description: > # this means to ignore newlines until "baseurl:"
  Coordinating the recovery and regeneration across the
  Upper Calder Valley: Mytholmroyd, Hebden Bridge and Todmorden.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /updates/:year/:month/:day/:title/
url: "http://floods.ucvr.org.uk" # the base hostname & protocol for your site
twitter_username: ucvr_
admin_twitter: dringtech

# Build settings
markdown: kramdown
